name: Build and Push Docker Images

on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-dev*'

  workflow_dispatch:
    inputs:
      image-version:
        description: Image version
        required: false
        type: string

env:
  PRODUCT_NAME: bot-openai

jobs:
  push-bot:
    runs-on: ubuntu-24.04
    steps:
    - name: Login ghcr.io
      shell: bash
      run: |
        docker login \
        --username ${{ github.repository_owner }} \
        --password ${{ secrets._GITHUB_PAT }} \
        ghcr.io
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get Docker image tag for ghcr.io
      id: docker-image-tag
      uses: Danand/docker-image-tag@v2-rc.8
      with:
        product-name: ${{ env.PRODUCT_NAME }}
        input-version: ${{ inputs.image-version }}
    - name: Build image of service
      shell: bash
      run: |
        docker build \
          --file=./bot/Dockerfile \
          --tag=${{ steps.docker-image-tag.outputs.image-tag }} \
          --progress="plain" \
          ./bot
    - name: Assign additional tags
      shell: bash
      run: |
        docker tag ${{ steps.docker-image-tag.outputs.image-tag }} ${{ steps.docker-image-tag.outputs.prefix }}:latest
    - name: Push image of service
      shell: bash
      run: |
        docker push ${{ steps.docker-image-tag.outputs.image-tag }}
